language: node_js

node_js:
  - node

env:
  global:
    - TZ=Asia/Tokyo
    - GIT_AUTHOR_NAME='Yuichi Tanikawa'
    - GIT_AUTHOR_EMAIL=u1.tanikawa@gmail.com
    - GIT_COMMITTER_NAME='Yuichi Tanikawa'
    - GIT_COMMITTER_EMAIL=u1.tanikawa@gmail.com

jobs:
  include:
    - script: npm test

    - stage: scrape
      if: type = cron AND branch = master
      script:
        - git checkout master
        - npm start
        - npm test
        - openssl aes-256-cbc -K $encrypted_c10fe768b1d7_key -iv $encrypted_c10fe768b1d7_iv -in deploy-key.enc -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - ./scripts/push-if-updated.sh ./data/*.json

notifications:
  slack:
    secure: TF072Z76yPpclwmKMX0VbHCHx1MUoqpm9+i+N0UNn6RZqu/J3ZphMMIqGfnDM+URQlPMFO9MhXa0dtNMvjU7eK++RPHCa7IKmKY7fFcJ7af6mRCmfJoy0Nfozhwd3Uiyznj986UqS9Q4cLZzGU7UL3N+cr1BXmZjvemXQQmtZ/Igt2xjyDWqxWxh4KRAXZitHpTTu1F4MsCcOfd4z9nuJkEBShN6fRTCkUwc+9JLshBkJxyH9DIEaM8iXepsltMufhcxrP7P7gRIR/y6gcQq7t/2+qP5JOajup315zIM9MzCzsf40Y2em+Z44G1i+H+zByGPoXry/0E4XBmTprAQDOovq0s49BCZj3EObIcwz07QkHcBlvFa2EeGR6+emxn7g6aKf4r0VrP7OSwhUZZKB3ilkl+DX1XwsqW5cgwME6J/WFpKbntgeG1NOAIqWYoLJoU46w/VKxncZkvaEsTAIAmbJKqYCskyV0GAZmvvBv9/8ZQl1rxYmgc2spffwJF//tru5po0yzatOY3vYI15ICjUb4pNoVJxofHDUMMOyC249Pq3HqlqoQubofR5X/R+9lURlW0cFnFmWDS0yX4AbnR0HpLQNUJTvN7l/xWLYvEC2RSXPMNs9Oy99dXtC2I+kJysQ4oqnWWsyU4n0FQHhqhhD9aLNbjL5FosY/KOLMQ=
