language: node_js
node_js:
- node
notifications:
  slack:
    secure: JQQm6e+Sl75QU4YUAwbYgab7dcQEwWVp/EwRjgvmImxEMc2XP8V4pSx4w+4bP74C0dBqoAYjTR1GJXq0vR8tQ7TSWWIlRw85tTK0FKwGJx9w4PcpIFbt6ZyIFmpNedQAGyaFOgrlmpKWPhiYAZTrOsHxyXsKKyUg9ysPIa3UeUMH/p667nlmw4+hUfCSdY73iaOF6gIvCnYxFtr0xTlwiSzZCwAKkYRKK5ZTHk/T8CLs/qh4YuYXJo8Zv+p0HDkgxNDC9/BW0FCeKdkKtz6lmbN4fq8BAFVfut/a8QwiJVwjXUFjbmhruz6/4x1zV0JNFiFjTfOr/zJUoF4+ogwL+yke5/9pv/qMNVz8Xx+Cup22FHsANgZME8BlFVxAN9OSgBzBlpeOrXPMlKzAvTRdwJ0SzqRaVgWTEyUW0c+EtXLlJstJJ+1P3hTMWVedZ+H9Gr9TRfDrrWLtrs0VOHXsSQSIwmJDNknI+RxPh+Qt321UzkaTf1+KT4WRZ4Bv+RpVHZYhlbuo4CfRrvlYgAztNNWLinWqwOXBgNum4ivz68Q+sV3FuATf696FmojdlZ6ngwLHg0m59iloUd6K7qUeVEPikFiQuxvDqjvEG+LgLSsUiw9L0rOIi/e9ztNsCsJxE+Aif7wXCi+xU3ookgV/j6iB+2V7/0Ecf4E6Cb97Qjg=
